### PR TITLE
chore: fix eslint warn(no-template-shadow)

### PR DESCRIPTION
**Pull request by libondev**
### Additional context

rt. 
image

### CODE REVIEW

**Review by antfu — COMMENTED** [review]
We don't have a parent scope `call`. I think it's that ESLint plugin get some false positive with line component at L63.

**Comment by libondev** [comment]
Yes, is it necessary for us to extract the RenderInput component into an external file separately to avoid this problem?

**Comment by libondev** [comment]
In addition, the final results of the following two submissions seem to have done nothing, because I originally wanted to reopen a pr, but because I know little about pr and don't know the rules in it, I am going to propose a new pr after this pr is closed or merged, and I have completed the function of data filtering in the new pr.

**Comment by libondev** [comment]
with https://github.com/antfu/regex-doctor/pull/8

**Pull request closed without merging**
